### ISSUE TITLE
Korean doesn't seem to work

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#2]
Submitting the test string to the /trans/ endpoint "曉城　趙　明基　博士　追慕　佛教　史學　論文集" I get an error:
```
scriptshifter     | INFO:scriptshifter.trans:Transliteration is from korean to Latin.
scriptshifter     | ERROR:scriptshifter.rest_api:Exception on /trans/korean [POST]
scriptshifter     | Traceback (most recent call last):
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
scriptshifter     |     response = self.full_dispatch_request()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
scriptshifter     |     rv = self.handle_user_exception(e)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
scriptshifter     |     rv = self.dispatch_request()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
scriptshifter     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
scriptshifter     |   File "/usr/local/scriptshifter/src/./scriptshifter/rest_api.py", line 81, in transliterate_req
scriptshifter     |     out = transliterate(in_txt, lang, r2s, capitalize)
scriptshifter     |   File "/usr/local/scriptshifter/src/./scriptshifter/trans.py", line 59, in transliterate
scriptshifter     |     cfg = load_table(lang)
scriptshifter     |   File "/usr/local/scriptshifter/src/./scriptshifter/tables/__init__.py", line 117, in load_table
scriptshifter     |     tdata = load(fh, Loader=Loader)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
scriptshifter     |     return loader.get_single_data()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
scriptshifter     |     node = self.get_single_node()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
scriptshifter     |     document = self.compose_document()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
scriptshifter     |     node = self.compose_node(None, None)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
scriptshifter     |     node = self.compose_mapping_node(anchor)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
scriptshifter     |     item_value = self.compose_node(node, item_key)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
scriptshifter     |     node = self.compose_mapping_node(anchor)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
scriptshifter     |     item_value = self.compose_node(node, item_key)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 82, in compose_node
scriptshifter     |     node = self.compose_sequence_node(anchor)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 111, in compose_sequence_node
scriptshifter     |     node.value.append(self.compose_node(node, index))
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
scriptshifter     |     node = self.compose_mapping_node(anchor)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
scriptshifter     |     item_value = self.compose_node(node, item_key)
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 64, in compose_node
scriptshifter     |     if self.check_event(AliasEvent):
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
scriptshifter     |     self.current_event = self.state()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
scriptshifter     |     if not self.check_token(KeyToken, ValueToken, BlockEndToken):
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 116, in check_token
scriptshifter     |     self.fetch_more_tokens()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 251, in fetch_more_tokens
scriptshifter     |     return self.fetch_double()
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 655, in fetch_double
scriptshifter     |     self.fetch_flow_scalar(style='"')
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 666, in fetch_flow_scalar
scriptshifter     |     self.tokens.append(self.scan_flow_scalar(style))
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 1152, in scan_flow_scalar
scriptshifter     |     chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
scriptshifter     |   File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 1213, in scan_flow_scalar_non_spaces
scriptshifter     |     raise ScannerError("while scanning a double-quoted scalar", start_mark,
scriptshifter     | yaml.scanner.ScannerError: while scanning a double-quoted scalar
scriptshifter     |   in "/usr/local/scriptshifter/src/scriptshifter/tables/data/korean.yml", line 17104, column 29
scriptshifter     | expected escape sequence of 4 hexadecimal numbers, but found 'n'
scriptshifter     |   in "/usr/local/scriptshifter/src/scriptshifter/tables/data/korean.yml", line 17104, column 43
```

**Comment by olovy** [comment]
Hi,

The problem seems to be these lines containing invalid unicode escape sequences (e.g. `\u030`)
```
17104    - "\uD5C8\uB4DD\uB7C9": "Ho\u0306 Tu\u030ng-nyang_"
33923    - "\uAC1C\uBCF": "kaebok_"
36281    - "Ho\u0306 Tu\u030ng-nyang": "\uD5C8\uB4DD\uB7C9_"
63564    - "kaebok": "\uAC1C\uBCF_"
```

In Libris we are are investigating using using your tables converted [1] to ICU transform rules [2] for automatic romanization.
[1] https://github.com/libris/librisxl/tree/develop/whelk-core/src/main/resources/romanizer/loc
[2] https://unicode-org.github.io/icu/userguide/transforms/general/rules.html

**Comment by scossu** [comment]
I see that the `\u030` in `Tu\u030ng` is not a valid Unicode sequence. I defer to a Korean specialist as to which symbol is meant to be placed there. 

Note that Korean transliteration & transcription will be completely overhauled in Phase 2 (current), and the current table won't be used. However, if the current table is of any use for the time being, it may be worth fixing it.

**Comment by scossu** [comment]
This highlights a separate problem: each table is only read (and validated) when transliteration is requested for the first time in the application life cycle for that particular table. This is done to reduce application startup time (especially with the huge Korean table), however it also hides problems like this one, when a table contains encoding errors, which are only caught when transliteration is requested. 

I think the best way to resolve this is to have automated tests built into a CI pipeline rather than forcing a read of all tables on startup.

**Comment by scossu** [comment]
Closing this as it's related to a Korean issue that no longer exists. #72 should cover the table parsing issue.
